### ISSUE TITLE
How does Authorization header works for the provided task url

### ISSUE THREAD

**Issue by jimmygns** [flamingo-run/django-cloud-tasks#37]
I read through the source code but couldn't find where it authenticates the OCID token. I was imagining something like [example](https://cloud.google.com/run/docs/authenticating/service-to-service#receive-request). Can someone show me some pointers? Appreciated.

**Comment by devo-wm** [comment]
@jimmygns did you ever receive an answer for this?

**Comment by joaodaher** [comment]
@jimmygns and @devo-wm , django-cloud-tasks do not perform any kind of authentication itself.
The [view](https://github.com/flamingo-run/django-cloud-tasks/blob/main/django_cloud_tasks/views.py#L18) has no custom authentication classes.

The [OIDC authentication is handled by the Cloud Run itself when is set to **private**](https://cloud.google.com/run/docs/triggering/using-tasks#creating_http_tasks_with_authentication_tokens), that is the supported configuration from this lib.

If you wish to manually check the OIDC (eg. you have a public Cloud Run service), you can:

- create a custom view to process tasks (you can inherit from [this one](https://github.com/flamingo-run/django-cloud-tasks/blob/main/django_cloud_tasks/views.py#L18))
- add your own authentication class that [handles OIDC](https://cloud.google.com/run/docs/authenticating/service-to-service#receive-request)
- set your view as the target for tasks by adding the Django settings `DJANGO_CLOUD_TASKS_URL_NAME` with the URL for this custom view

**Comment by joaodaher** [comment]
We already have a PR that will implement this: https://github.com/flamingo-run/django-cloud-tasks/pull/45/files
