### ISSUE TITLE
Setting up a recurrent task

### ISSUE THREAD

**Issue by AnselmC** [flamingo-run/django-cloud-tasks#55]
Hey, thanks for this package.

I have a question on setting up a recurrent task.

I defined a current task as you did in the README and then ran the `schedule_tasks` management command.
However, all I get as output is:
```
Successfully scheduled 0 tasks to domain http://localhost:8080
```
Is there additional setup required for registering the task? 
(I briefly parsed the source code but thought it may be more efficient to ask directly)

Also, what should the value of `DJANGO_CLOUD_TASKS_ENDPOINT` be? Just the URL of my deployment?

**Comment by joaodaher** [comment]
> Is there additional setup required for registering the task?

You must be sure that the code where your task lives in are imported during Django setup, pretty much like Django signals require you to import them.

I usually import them in the app's setup. [Here's an example](https://github.com/flamingo-run/django-cloud-tasks/blob/main/sample_project/sample_app/apps.py#L8).

> what should the value of DJANGO_CLOUD_TASKS_ENDPOINT be? Just the URL of my deployment?

Yes!
The URL that Google Cloud Tasks will call to invoke a task.

If you're using Cloud Run, it can be the service URL.

**Comment by AnselmC** [comment]
Ok thanks. I've abandoned GCP in the meantime so won't be able to verify this works
